name: Deploy to AWS S3 and CloudFront

on:
  push:
    branches:
      - master # Deploy to Prod
      - develop # Deploy to Stage

jobs:
  deploy:
    runs-on: ubuntu-latest

    # Dynamically assign the environment based on the branch
    environment: ${{ github.ref_name == 'master' && 'Prod' || 'Stage' }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies and Build
        run: |
          npm install
          npm run build

      - name: Sync S3 Bucket
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: "dist"

      - name: Invalidate CloudFront Cache
        uses: awact/cloudfront-action@master
        env:
          SOURCE_PATH: "/*"
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DISTRIBUTION_ID: ${{ secrets.DISTRIBUTION_ID }}
